export const data = [
  {
    titulo: "Termometro Caseiro",
    figura: "/assets/termometro.jfif",
    resumo: " ",
    item: {
      a: "Garrafa de plástico pequena",
      b: "Água colorida",
      c: "Canudo de plástico",
      d: "Supercola ou fita adesiva",
      e: "Marcador ou etiquetas para a escala",
      f: null,
      g: null,
      h: null,
      i: null,
      j: null,
    },
      procedimento:"1- Lave e seque bem a garrafa de plástico.<br>2 - Encha cerca de um quarto da garrafa com água colorida. Isso servirá como o líquido dentro do termômetro.<br>3 - Coloque o canudo dentro da garrafa, deixando-o submerso na água, mas não encostando no fundo.<br> 4 - Cole o canudo na posição com supercola ou use fita adesiva para mantê-lo no lugar.<br> 5 - Marque a posição inicial da água no canudo com um marcador ou etiqueta. Isso será a referência para a temperatura ambiente.<br> 6 - Coloque o termômetro em diferentes condições de temperatura para observar como a água sobe ou desce no canudo. Marque as diferentes posições da água com o marcador ou etiquetas.<br> 7 - Agora você tem um termômetro caseiro simples!",
    video: "https://www.youtube.com/embed/Wy3QMieyN_Q",
    },
    {
    titulo: "Calor específico dos metais",
    figura: "/assets/metais.jpg",
    resumo: " <br>",
    item: {
      a: "Panela ou recipiente de metal",
      b: "Termômetro",
      c: "Água",
      d: "Fonte de calor",
      e: "Panela ou recipiente de metal",
      f: "Diferentes amostras de metais",
      g: "Balança",
      h: "",
      i: "",
      j: "",
    },
    procedimento:
      "1 - Coloque uma quantidade conhecida de água na panela ou recipiente de metal e aqueça-a até uma temperatura elevada,porém, abaixo do ponto de ebulição.<br> 2 - Meça a temperatura inicial da água e anote-a.<br> 3 - Com cuidado, adicione uma amostra de metal de massa conhecida na água quente.<br> 4 - Monitore e registre a temperatura final da mistura até que ela atinja o equilíbrio térmico.<br> 5 - Utilize a variação de temperatura, a massa do metal e a massa da água para calcular o calor específico do metal. ",
    video: "https://www.youtube.com/embed/Wy3QMieyN_Q",
  },
  {
    titulo: "Fusão de gelo",
    figura: "/assets/gelo.jpg",
    resumo:
      "<br>Determinar o calor latente de fusão do gelo usando um calorímetro caseiro.<br>",
    item: {
      a: "Recipiente isolante (pode ser uma caixa de isopor ou um pote térmico)",
      b: "Água",
      c: "Gelo",
      d: "Fonte de calor",
      e: "Termometro",
      f: "",
      g: "",
      h: "",
      i: "",
      j: "",
    },
    procedimento:
      "1 - Coloque uma quantidade conhecida de gelo em <br> um recipiente isolante.<br> 2 - Meça a temperatura inicial do gelo e anote-a.<br> 3 - Aqueça uma pequena quantidade de água até uma<br> temperatura próxima ao ponto de ebulição.<br> 4 - Despeje a água quente sobre o gelo no recipiente<br> isolante.<br> 5 - Monitore e registre a temperatura da mistura até<br> que todo o gelo tenha derretido.<br> 6 - Utilize a variação de temperatura e a quantidade de <br> gelo derretido para calcular o calor latente de fusão do gelo.<br>",
    video: "https://www.youtube.com/embed/kfR3QFhdfoo",
  },

  {
    titulo: "Estado da matéria",
    figura: "/assets/EstadosMateria.avif ",
    resumo:
      "A matéria é tudo o que ocupa espaço e possui massa. Ela pode ser encontrada em diversos estados, dependendo das condições de temperatura e pressão a que está sujeita. Os três estados mais comuns da matéria são sólido, líquido e gasoso, cada um deles com características únicas que definem suas propriedades e comportamentos. Esses estados da matéria são fundamentais para a compreensão da física e da química, pois afetam o comportamento e as propriedades das substâncias em nosso mundo. <br> Sólido:<br> Quando algo é sólido, é como uma pedra ou gelo, por exemplo. Ele mantém a mesma forma o tempo todo e você não pode espremê-lo ou moldá-lo facilmente. Os átomos(menores partículas que formam a matéria) ou pedaços que compõem o sólido ficam bem juntinhos e não se movem muito. <br> Líquido:<br> Os líquidos são como a água, o suco ou o leite. Eles não têm uma forma fixa e podem se espalhar para preencher qualquer espaço. Imagine despejar água em um copo : ela assume a forma do copo. Os átomos ou partículas em um líquido ficam um pouco mais soltos do que em um sólido, mas ainda assim mais unidos que em um gás. <br> Gasoso: <br> O estado gasoso é como o ar que respiramos. Os gases não têm forma nem volume fixos, eles se espalham para ocupar todo o espaço disponível. As partículas em um gás estão muito afastadas e se movem rapidamente e aleatoriamente(como se estivessem dançando)",
    item: {
      a: "Panela",
      b: "Água",
      c: "Gelo",
      d: "Fonte de calor",
      e: "Termometro",
      f: "Sal",
      g: "Caneta e papel para registro de observações",
      h: "Copos",
      i: "",
      j:"",
    },
    procedimento:
      "Parte 1: Fusão (Mudança de Sólido para Líquido) <br>Coloque meio copo de água em uma panela e coloque-a no fogão. <br>Aqueça a água até que comece a ferver (100°C).<br>Registre a temperatura da água enquanto ela aquece. <br>Observe o que acontece com a água à medida que ela aquece e registre suas observações. Você deve notar a formação de bolhas e vapor. <br><br> Parte 2: Solidificação (Mudança de Líquido para Sólido)<br>Coloque um pouco de água em recipiente de plástico e coloque-o no freezer ou congelador. <br>Deixe a água congelar por algumas horas.<br>Retire o recipiente e observe o que aconteceu com a água. Toque no gelo e registre suas observações.<br><br>Parte 3: Vaporização (Mudança de Líquido para Gasoso)<br>Despeje uma pequena quantidade de água em um copo transparente<br>Aqueça o copo com água no micro-ondas por cerca de 30 segundos.Observe o que acontece com a água e registre suas observações. Você deve ver a formação de vapor na parte interna do copo.<br><br> Parte 4: Condensação (Mudança de Gasoso para Líquido)<br>Encha outro copo com água quente. Coloque o copo em um ambiente frio, como uma janela ou geladeira <br>Observe o que acontece com o copo e registre suas observações. Deve haver gotas de água formando-se na parte externa do copo.<br><br>Parte 5: Experimento Adicional - Efeito do Sal na Solidificação<br>Repita o procedimento da Parte 2, mas desta vez adicione uma pequena quantidade de sal à água antes de congelá-la.<br>Compare o tempo que leva para a água congelar com e sem sal. Registre suas observações.<br>Análise de Resultados:<br>1- Compare as mudanças de estado físico da água nas diferentes partes do experimento.<br>2-Discuta as observações e explique os conceitos por trás das mudanças de estado, como temperatura, pressão e energia. <br>3-Comente sobre como o sal afetou o processo de solidificação",
    video: "https://youtu.be/sOf0NvdGSQg?si=5LY-LwM7yKpXwoZx",
  },
  {
    titulo: "Transferência de calor",
    figura: "assets/transferencia.jpg ",
    resumo:
      "A transferência de calor é exatamente essa transferência de energia que pode fazer com que um objeto mude de estado físico, e ela pode acontecer por três modos diferentes:<br>Condução:<br>Imagine você segurando uma barra de metal quente em uma ponta. A energia térmica no metal começa a se espalhar ao longo da barra em uma espécie de 'corrida quente'. É como uma partida de revezamento de partículas, onde as mais agitadas passam o bastão (energia) para as próximas. A energia térmica segue essa corrida até que a velocidade das partículas diminua. Quando dois objetos atingem a mesma temperatura, eles atingem o equilíbrio térmico. Confira aqui um experimento que mostra a condução!<br>Convecção:<br>Agora, vamos pensar em uma panela de água fervente. A água quente perto do fundo da panela começa a fazer um movimento para cima. À medida que a água quente sobe, a água fria desce para tomar o seu lugar. Isso cria um movimento constante, espalhando o calor pela panela. Isso também acontece com as correntes de ar, ou seja, o ar quente sobe e o ar frio desce! <br>Irradiação:<br>A irradiação é como um show de luzes no espaço. Imagine estar ao sol, sentindo o calor acariciando sua pele. Isso acontece porque o sol está disparando ondas de energia térmica, como raios de calor e luz, diretamente para a Terra. Não há necessidade de um mensageiro ou de um meio material; o calor vem diretamente até você, como um abraço quente do sol. Assim sendo, percebe-se que não há contato! Ela pode também ser observada em uma fogueira: a maioria das pessoas não tem que entrar dentro dela para se aquecer! A irradiação é o único modo de transferir calor no vácuo do espaço.<br>Essas são as maneiras pelas quais o calor é transmitido. Ter um bom entendimento desses processos é fundamental, desde cozinhar uma refeição saborosa até entender o funcionamento de máquinas e sistemas de aquecimento em nossas casas. É como um verdadeiro espetáculo de ciência em ação!",
    item: {
      a: "Três copos transparentes",
      b: "Corante alimentar(opcional)",
      c: "Água",
      d: "Gelo(opcional)",
      f: "Fonte de calor",
      g: "Caneta e papel para registro de observações",
      h: "",
      i: "",
      j: "",
    },
    procedimento:
      "Parte 1: Condução<br>Encha um recipiente com água quente (não ferva) e adicione algumas gotas de corante alimentar (opcional).<br>Encha outro recipiente com água fria. Coloque um pedaço de metal ou plástico no recipiente com água quente.<br>Coloque um pedaço de metal ou plástico no recipiente com água fria. Observe como o calor é transferido através dos materiais. Registre suas observações.<br><br>Parte 2: Convecção<br>a convecção pode ser observada no funcionamento de uma panela de pressão. agora, adaptando para uma atividade mais segura, faremos o seguinte:<br>Aproveitando a última atividade, pegue um terceiro copo e encha metade com a água quente e metade com a água fria. Observe que a água quente sobe e a água fria desce.<br><br>Parte 3: Radiação Térmica<br>Encha um recipiente com água em temperatura ambiente. Coloque o recipiente em uma área com sol.Observe como o calor do sol ou da fonte de calor aquece a água no recipiente, mesmo sem contato direto. Registre suas observações.<br><br>Parte 4: Experimento Adicional - Transferência de Calor com Gelo<br>Coloque um cubo de gelo em cada um dos recipientes usados nas partes anteriores do experimento, e outro em um local com luz do Sol.<br>Observe como o gelo se comporta em cada um após dois minutos.Registre suas observações. <br>Qual tipo de transferência de calor aconteceu em cada caso?<br>Qual a temperatura da água em cada copo após o derretimento do gelo? Use o termômetro caseiro.<br>Análise de Resultados:<br>1- Reflita sobre os três métodos de transferência de calor (condução, convecção e radiação) observados no experimento. <br>2-Qual a importância da transferência de calor em processos naturais e cotidianos?",
    video: "https://youtu.be/caUJLKi54ZU?si=1jOS0T4mmqY5jkT7",
  },
  {
    titulo: "Materiais isolantes e materiais condutores",
    figura: "/assets/condutores.webp",
    resumo:
      "A capacidade dos materiais de transmitir ou armazenar calor depende do tipo de material. Alguns materiais podem segurar muito calor sem esquentar muito rápido, como a água, enquanto outros aquecem ou esfriam rapidamente, como os metais. Essas diferenças na capacidade de transmitir ou armazenar calor são fundamentais para diversos processos e aplicações na vida cotidiana e na indústria. .Os condutores são aqueles que transmitem o calor com maior facilidade, já os isolantes, dificultam sua saída. <br>Materiais Condutores: <br>Os materiais condutores são como 'corredores de calor'. Eles são bons em transferir calor rapidamente. Pense em uma colher de metal tocando seu café. O calor do café é absorvido pela colher e viaja rapidamente para sua mão, o que pode fazer você sentir calor. <br>Exemplos de materiais condutores incluem metais como ferro, alumínio e cobre. Isso é por isso que panelas são feitas de metal; elas espalham o calor uniformemente para cozinhar alimentos de maneira eficaz.<br>Materiais Isolantes:<br>Por outro lado, os materiais isolantes são como 'guardiões do frio'. Eles não deixam o calor passar facilmente. Pense em uma caixa de isopor. Quando cheia de gelo, por exemplo, pode deixar o que for colocado dentro dela a baixa temperatura por um longo período de tempo, pois impede o calor de fora da caixa de alcançar o que está dentro. Isso também funciona com um cobertor, que mantém o calor dentro dele e impede que este se disperse no ambiente.<br>Exemplos de materiais isolantes incluem madeira, plástico, espuma e lã. Esses materiais são usados em isolamento de casas, casacos de inverno e até em luvas de forno, para proteger nossas mãos do calor.",
    item: {
      a: "1 colher de metal",
      b: "1 colher de madeira",
      c: "1 copo com água muito gelada",
      d: "1 copo com água quente",
      e: "Luvas de proteção ou um pano de prato",
      f: "Termômetro",
      g: "Cronômetro",
      h: "Caneta e papel para registro de observações",
      i: "",
      j: "",
    },
    procedimento:
      "Parte 1: Preparação<br>Prepare todos os objetos(colheres) em temperatura ambiente. Certifique-se de tomar cuidado para manusear os materiais durante o experimento. Certifique-se da presença de um adulto responsável. <br><br>Parte 2: Teste de Condução de Calor<br>Meça a temperatura inicial da colher de metal e registre no papel. Mergulhe a colher no copo de água quente por cerca de 1 minuto - proteja sua mão com o pano Remova a colher do calor, meça a temperatura dela e registre no papel.Coloque a colher em um recipiente com água fria.Registre o tempo que a colher demora para esfriar até os 20 °C. <br><br>Parte 3: Teste de Isolantes Térmicos<br>Meça a temperatura inicial da colher de madeira e registre no papel. Mergulhe a colher no copo de água quente até que ela alcance a mesma temperatura que a colher de metal quando aquecida - proteja sua mão com o pano! Remova a colher do calor e registre no papel o tempo que ela levou para chegar até aquela temperatura.Coloque a colher em um recipiente com água fria.Registre o tempo que a colher demora para esfriar até os 20 °C.<br>Análise de Resultados:<br>1-Compare os tempos de aquecimento e  resfriamento da colher  metálica com o da colher de madeira.Você percebeu como os materiais metálicos, sendo condutores de calor, resfriam mais rapidamente do que os materiais isolantes?<br>2- Explique a diferença entre materiais condutores e isolantes, com base  no experimento e usando suas próprias palavras",
    video: "https://youtu.be/ySIZdwTZH_w?si=-ceR0TIe35Um6VWu",
  },
  {
    titulo: "Calorímetro",
    figura: "/assets/calorimetro.webp ",
    resumo: "Um calorímetro é um aparelho simples e útil usado para medir a quantidade de calor que um objeto libera ou absorve durante uma reação química ou um processo físico. Imagine que você está fazendo um experimento em que quer saber quanto calor é gerado quando você queima um pedaço de papel.<br><br>Para fazer isso, você coloca o papel no calorímetro, que é basicamente uma \"casinha\" especial para o papel. Dentro do calorímetro, há água ou outro líquido que ajuda a absorver o calor. Quando você queima o papel, o calor produzido faz a temperatura da água aumentar.<br><br>Então, você mede a mudança de temperatura da água e, usando uma fórmula, pode calcular a quantidade exata de calor liberada pelo papel. É como se o calorímetro fosse um detetive que nos ajuda a descobrir quanto calor está envolvido em uma situação.<br><br>Em resumo, um calorímetro é como uma \"balança\" de calor que nos ajuda a medir o calor gerado ou absorvido em diferentes situações, como reações químicas, e é uma ferramenta importante em laboratórios para entender melhor como as coisas esquentam ou esfriam.",
    item: {
         a: "lata de metal",
        b: "termômetro",
        c: "placa de isopor (ou papelão - não terá tanta eficácia!)",
        d: "copo de medidas",
        e: "Fita adesiva",
        f: "Caneta e papel para registro de observações",
        g:"",
        h: "",
      i: "",
      j: "",
    },
    procedimento: "Parte 1: Montagem do Calorímetro<br>Com a ajuda de um adulto, corte a parte superior da lata de metal. O resultado deve parecer com um copo.<br>Lave a lata, tomando cuidado com a borda cortada, pois ela é muito cortante.<br>Peça para um adulto dobrar um pouco das beiradas, para que o manuseio da lata se torne mais seguro<br><br>Agora, prepare o isopor. Corte uma caixa a partir dele que cubra completamente a lata, sem sobrar espaços. Siga as instruções do vídeo abaixo em caso de dúvida.<br>Com uma fita adesiva, prenda as peças de isopor na posição correta<br>Se não for possível usar o isopor, faça os passos acima com papelão, colando duas placas, uma sobre a outra, para ter um melhor efeito. (não passe fita na tampa!)<br><br>Após a caixa completa e a lata posicionada, faça um furo na tampa para colocar o termômetro.<br>Agora, na simulação, teste o aumento de temperatura.<br>O que acontece com a pressão?<br>O que acontece com as partículas dentro do calorímetro?<br>O que acontece com o volume?",
    video: "https://youtu.be/ydmT3dPKs9Y?si=zaaZc7D3dLmheX7l",
},
{
  titulo: "Testes com Calorímetro",
  figura: "/assets/calorimetro2.webp",
  resumo: "Após montar o calorímetro caseiro, você pode realizar diversos testes para medir a capacidade térmica de diferentes substâncias.",
  item: {
    a: "Calorímetro caseiro",
    b: "Colher (ou garfo)",
    c: "Pedrinha",
    d: "Caneta e papel para registro de observações",
    e: "Água",
    f: "Termômetro",
    g:"",
    h: "",
      i: "",
      j: "",
  },
  procedimento: "Encha o calorímetro com 200 ml de água e meça a temperatura inicial.<br>Mergulhe a pedra em água quente por 1 minuto, retire-a com a ajuda de uma colher, e coloque-a na água dentro do calorímetro.<br>Registre a temperatura da água no calorímetro após 1 minuto e, em um tempo determinado, registre novamente a temperatura.<br>Calcule a variação de temperatura da água no calorímetro para cada substância de teste usando a fórmula Q = mcΔT, onde Q é a quantidade de calor transferida, m é a massa da substância, c é a capacidade térmica da água (4,18 J/g°C), e ΔT é a variação de temperatura (temperatura final - temperatura inicial).",
  video: "https://youtu.be/UZhhqtk4rbA?si=RyJQ69OXv0HyVokg",
},
{
  titulo: "Calor Latente",
  figura: "/assets/latente.webp",
  resumo: "O calor latente é um conceito importante relacionado às mudanças de fase das substâncias, como a transição de sólido para líquido ou líquido para gasoso.",
  item: {
    a: "Gelo",
    b: "Copo de medição",
    c: "Termômetro",
    d: "Panela",
    e: "Fogão ou placa de aquecimento",
    f: "Cronômetro",
    g: "Caneta e papel para registro de observações",
    h: "",
      i: "",
      j: "",
  },
  procedimento: "Parte 1: Medição da Temperatura Inicial<br>1. Coloque um cubo de gelo no copo de medição.<br>2. Meça e registre a temperatura inicial do gelo usando o termômetro.<br>Parte 2: Fusão do Gelo<br>1. Coloque o gelo do copo de medição em uma panela.<br>2. Aqueça a panela no fogão ou placa de aquecimento em fogo baixo.<br>3. Continue aquecendo o gelo até que ele derreta completamente.\n4. Registre o tempo que leva para todo o gelo derreter.<br><br>Parte 3: Medição da Temperatura Final<br>Após a fusão completa do gelo, meça e registre a temperatura da água resultante na panela.<br><br>Análise de Resultados:<br>1. Calcule a variação de temperatura (ΔT) entre a temperatura final e a temperatura inicial da água (ΔT = Temperatura Final - Temperatura Inicial).<br>2. Use a fórmula Q = m * L, onde Q é o calor latente da fusão, m é a massa de gelo derretido e L é o calor latente da fusão da água (aproximadamente 334 J/g).<br>3. Calcule o calor latente da fusão do gelo usando a massa de gelo e a variação de temperatura medida.<br>4. Compare o valor calculado com o valor conhecido do calor latente da fusão da água (334 J/g) e discuta qualquer diferença observada.",
  video: "https://youtu.be/op5vkU5srAM?si=Wmxucg65R-NFEyrZ",
},
{
  titulo: "Calor Específico",
  figura: "/assets/especifico.jpg",
  resumo: "O calor específico é outro conceito importante relacionado ao calor, mas envolve a capacidade de um material para armazenar calor sem aumentar rapidamente a sua temperatura.<br><br>Em termos simples, cada material tem uma capacidade diferente de \"segurar\" calor. Alguns materiais, como a água, têm um alto calor específico, o que significa que eles podem absorver uma quantidade significativa de calor sem que sua temperatura suba muito. Por exemplo, a água precisa de uma quantidade considerável de calor para aquecer ou resfriar, o que a torna excelente para regular a temperatura em nosso planeta.<br><br>Por outro lado, materiais com baixo calor específico, como os metais, aquecem ou resfriam rapidamente com a adição ou remoção de calor. Isso é por isso que o metal de uma panela fica quente rapidamente quando você o coloca no fogão.<br><br>O calor específico é importante em muitas aplicações práticas, desde o projeto de sistemas de aquecimento e resfriamento em casas até a escolha de materiais para construir coisas como foguetes ou cozinhar alimentos. Em resumo, o calor específico nos ajuda a entender como diferentes materiais respondem ao calor e é crucial em muitos aspectos da nossa vida cotidiana.",
  item: {
      a: "Água",
      b: "Panela",
      c: "Fogão ou placa de aquecimento",
      d: "Cronômetro",
      e: "Termômetro",
      f: "Copo de medição",
      g: "Caneta e papel para registro de observações",
      h: "",
      i: "",
      j: "",
  },
  procedimento: "Parte 1: Preparação<br><br>1. Coloque uma quantidade conhecida de água no copo de medição (por exemplo, 200 ml).<br>2. Meça e registre a temperatura inicial da água usando o termômetro.<br><br>Parte 2: Aquecimento da Água<br><br>1. Despeje a água do copo de medição em uma panela.<br>2. Aqueça a água na panela no fogão ou placa de aquecimento em fogo baixo.<br>3. Continue aquecendo a água e registre o tempo que leva para aumentar sua temperatura em uma quantidade específica (por exemplo, 10°C).<br><br>Parte 3: Medição da Temperatura Final<br><br>1. Após a água atingir a variação de temperatura desejada (por exemplo, 10°C a mais que a temperatura inicial), meça e registre a temperatura final da água.<br><br>Análise de Resultados<br><br>1. Calcule a variação de temperatura (ΔT) entre a temperatura final e a temperatura inicial da água (ΔT = Temperatura Final - Temperatura Inicial).<br>2. Use a fórmula Q = m * c * ΔT, onde Q é o calor transferido para a água, m é a massa de água aquecida e c é o calor específico da água (aproximadamente 4,18 J/g°C).<br>3. Calcule o calor específico da água usando a massa de água, a variação de temperatura medida e a quantidade de calor transferida.<br>4. Compare o valor calculado com o valor conhecido do calor específico da água (4,18 J/g°C) e discuta qualquer diferença observada.",
  video: "https://youtu.be/Nh-7P0q1iuc?si=zMjfIWgtfEqFz5jC",
}
,
{
  titulo: "Estimativa do Derretimento do Chocolate",
  figura: "/assets/chocolate.jpg",
  resumo: "Chegou a hora de um experimento delicioso! Calcular uma estimativa do derretimento do chocolate é muito importante na hora de usá-lo para cozinhar, pois sua temperatura de preparo afeta como ele se comporta após resfriado. Aqui estão os passos básicos para fazer essa estimativa:",
  item: {
    a: "Chocolate em barra",
    b: "Termômetro",
    c: "Panela",
    d: "Água",
    e: "Fogão ou placa de aquecimento",
    f: "Colher de metal",
    g: "Caneta e papel para registro de observações",
    h: "Prato (opcional)",
      i: "",
      j: "",
  },
  procedimento: "Parte 1: Preparação\n\n1. Quebre ou corte o chocolate em pedaços pequenos e uniformes para facilitar o derretimento.\n2. Prepare o termômetro para medir a temperatura.\n\nParte 2: Derretendo o Chocolate\n\n1. Encha uma panela com água até cerca de um terço de sua capacidade.\n2. Coloque a panela no fogão ou placa de aquecimento e ligue-o em fogo baixo.\n3. Espere até que a água comece a aquecer, mas não deixe ferver.\n4. Coloque uma tigela resistente ao calor sobre a panela para criar um banho-maria improvisado.\n5. Adicione os pedaços de chocolate na tigela.\n6. Mexa suavemente o chocolate com uma espátula de silicone ou colher de metal enquanto ele derrete.\n7. Use o termômetro para medir a temperatura do chocolate em intervalos regulares.\n\nParte 3: Registro de Observações\n\n1. Registre a temperatura inicial do chocolate antes de começar a aquecer.\n2. Continue aquecendo e mexendo o chocolate até que ele esteja completamente derretido e atinja uma consistência suave.\n3. Registre a temperatura do chocolate quando estiver completamente derretido.\n4. Pare de aquecer o chocolate e desligue o fogão ou a placa de aquecimento.\n\nParte 4: Análise de Resultados\n\n1. Calcule a variação de temperatura (ΔT) entre a temperatura final e a temperatura inicial do chocolate.\n2. Discuta como o chocolate passou do estado sólido para o líquido à medida que aqueceu e atingiu seu ponto de derretimento.\n3. Explore a ideia de que diferentes tipos de chocolate podem ter pontos de derretimento ligeiramente diferentes, dependendo de sua composição.\n\nParte 5: Experimento Adicional (Opcional)\n\n1. Se desejar, despeje o chocolate derretido em um prato.\n2. Coloque o prato na geladeira para que o chocolate endureça novamente.\n3. Compare a textura e o sabor do chocolate derretido com o chocolate endurecido.",
  video: "https://youtu.be/4lXxQ0HrALk?si=UiAREx814e3CfDwz",
},
{
  titulo: "Misturas",
  figura: "/assets/mistura.webp",
  resumo: "Quando a água é misturada com sal, tanto o ponto de ebulição quanto o ponto de congelamento da água são afetados, resultando em um aumento da temperatura de ebulição e em uma diminuição da temperatura de congelamento em relação à água pura. Em outras palavras, as misturas de água e sal apresentam um ponto de ebulição mais alto e um ponto de congelamento mais baixo do que a água pura.<br><br>A adição de sal à água interrompe as ligações de hidrogênio entre as moléculas de água, tornando mais difícil para elas mudarem de estado. Isso significa que é necessário aquecer a água a uma temperatura mais alta do que 100°C (ponto de ebulição da água pura a nível do mar) para que ela entre em ebulição quando há sal dissolvido. Da mesma forma, a água salgada congela a temperaturas mais baixas do que 0°C (ponto de congelamento da água pura), tornando-se líquida em temperaturas negativas.",
  item: {
    a: "Água",
    b: "Sal de cozinha (cloreto de sódio)",
    c: "Panela",
    d: "Fogão ou placa de aquecimento",
    e: "Termômetro",
    f: "Dois copos ou recipientes transparentes",
    g: "Luvas de proteção (para manusear objetos quentes)",
    h: "Cronômetro",
    i: "Caneta e papel para registro de observações",
      j: "",
  },
  procedimento: "Parte 1: Ponto de Ebulição\n\nAquecimento da Água Pura:\n1. Encha uma panela com 200ml de água e coloque-a no fogão.\n2. Aqueça a água até que ela comece a ferver.\n3. Registre a temperatura da água quando começar a ferver e observe o processo.\n\nAquecimento da Água com Sal:\n1. Limpe a panela usada anteriormente e encha-a novamente com 200ml de água.\n2. Adicione uma colher de sopa de sal de cozinha à água.\n3. Aqueça a água com sal até que ela comece a ferver.\n4. Registre a temperatura da água com sal quando começar a ferver e observe o processo.\n\nParte 2: Ponto de Congelamento\n\nCongelamento da Água Pura:\n1. Encha um copo ou recipiente com água pura.\n2. Coloque-o no freezer e aguarde até que a água esteja completamente congelada.\n3. Registre a temperatura do congelamento da água (geralmente próximo a 0°C).\n\nCongelamento da Água com Sal:\n1. Encha outro copo ou recipiente com água e adicione a mesma quantidade de sal de cozinha usada anteriormente.\n2. Coloque-o no freezer e aguarde até que a água com sal esteja completamente congelada.\n3. Registre a temperatura do congelamento da água com sal e observe qualquer diferença.\n\nAnálise de Resultados:\nCompare as temperaturas de ebulição e congelamento da água pura e da água com sal.\nDiscuta como a adição de sal afeta os pontos de ebulição e congelamento da água.\nExplique os conceitos por trás dessas mudanças, relacionando-as com a diminuição da pressão de vapor e a mudança na estrutura das moléculas de água devido à presença do sal.",
  video: "https://youtu.be/Jdw9VeN5glo?si=su3SremtZtyN2zMW",
},
{
  titulo: "Resfriamento ",
  figura: "/assets/resfriamento.jpg",
  resumo: "Quando alguém deseja resfriar ou aquecer algo, a superfície onde o objeto é colocado desempenha um papel importante. Se a superfície for lisa e plana, como uma mesa de vidro ou metal, o processo de esfriamento ou aquecimento tende a funcionar de maneira mais eficiente. Isso acontece porque a superfície plana permite que o calor seja transferido de forma mais eficaz. O calor é trocado de energia quando o objeto toca essa superfície. Porém, se a superfície não for lisa, como uma pedra irregular, o processo pode ser menos eficaz. Isso ocorre porque as partes ásperas ou irregulares podem dificultar a troca de calor. Pode-se pensar que há pequenos espaços de ar entre o objeto e a superfície, o que torna mais difícil para a pessoa esfriar ou aquecer o objeto de forma rápida e uniforme. Em resumo, a escolha da superfície onde o objeto é colocado para esfriar ou aquecer desempenha um papel importante. Superfícies planas funcionam melhor para transferir calor, enquanto superfícies irregulares podem tornar o processo mais difícil. Portanto, a pessoa deve considerar cuidadosamente onde colocar o objeto para fazer isso de maneira eficiente.",
  item: {
    a: "200 ml de água",
    b: "Um pote plano (como uma bandeja rasa)",
    c: "Um copo",
    d: "Termômetro",
    e: "Cronômetro",
    f: "Caneta e papel para registro de observações",
    g:"",
    h: "",
    i: "",
    j: "",
  },
  procedimento: "Parte 1: Preparação<br>Meça e despeje 200 ml de água quente em um copo e em um pote plano (certifique-se de que a água nas duas fontes esteja à temperatura ambiente).<br>Parte 2: Medição da Temperatura Inicial<br>Meça e registre a temperatura inicial da água nos dois recipientes usando o termômetro. Certifique-se de registrar a temperatura inicial de ambos simultaneamente.<br>Parte 3: Resfriamento da Água<br>Coloque o copo e o pote plano em um local onde a temperatura ambiente seja constante (evite correntes de ar).<br>Inicie o cronômetro. A intervalos regulares (por exemplo, a cada 5 minutos), meça e registre a temperatura da água em cada recipiente.<br>Continue medindo até que a temperatura da água em ambos os recipientes atinja um valor significativamente mais baixo, ou até que não ocorra mais mudança de temperatura após várias medições.<br>Parte 4: Análise de Resultados<br>Observe e registre o tempo necessário para que a temperatura da água em cada recipiente alcance um valor específico (por exemplo, 10°C abaixo da temperatura inicial). Analise as diferenças nos tempos de resfriamento e na taxa de resfriamento entre os dois recipientes. Discuta como a forma e a superfície de contato com o ambiente podem afetar a taxa de resfriamento da água.",
  video: "https://youtu.be/Hd4fDE91III?si=xxhAj6lsjV0a7V6g",
},
{
  titulo: "Aquecimento",
  figura: "/assets/aquecimento.jpg",
  resumo: "Neste experimento, será evidenciado um interessante efeito, que permitirá estudar calor específico e condutividade dos materiais: testaremos como diferentes objetos podem ser aquecidos em um mesmo tempo.",
  item: {
    a: "Uma colher de metal",
    b: "Uma colher de madeira",
    c: "Uma panela",
    d: "Fogão ou placa de aquecimento",
    e: "Água",
    f: "Termômetro",
    g: "Cronômetro",
    h: "Luvas de proteção térmica",
    i: "Caneta e papel para registro de observações",
      j: "",
  },
  procedimento: "Parte 1: Preparação<br>Encha a panela com água suficiente para submergir totalmente as colheres.<br>Coloque o termômetro na panela para monitorar a temperatura da água.<br>Coloque as colheres (uma de metal e uma de madeira) ao lado da panela.<br>Parte 2: Aquecimento das Colheres<br>Ligue o fogão ou a placa de aquecimento em fogo médio.<br>Coloque as duas colheres na água quente na panela ao mesmo tempo.<br>Inicie o cronômetro para registrar o tempo.<br>Parte 3: Medição da Temperatura<br>Monitore a temperatura da água na panela usando o termômetro.<br>Registre a temperatura da água a intervalos regulares (por exemplo, a cada minuto) durante um período de tempo definido (por exemplo, 5 minutos).<br>Parte 4: Análise de Resultados<br>Compare as mudanças de temperatura das colheres de metal e de madeira ao longo do tempo.<br>Discuta como as colheres de metal, sendo boas condutoras de calor, absorvem calor mais rapidamente da água quente e, portanto, aumentam sua temperatura mais rapidamente em comparação com a colher de madeira.<br>Explique como a capacidade de condução de calor está relacionada ao material das colheres e como isso afeta seu comportamento quando aquecidas.",
  video: "https://youtu.be/H99synPKR-4?si=hP7IA7qEisrlPgMT",
},
{
  titulo: "Variação de Temperatura de Misturas",
  figura: "assets/variacao.jpg",
  resumo: "Este experimento permitirá perceber melhor o efeito retratado no conteúdo de variação de misturas. Será feito o seguinte: será misturada quantidades diferentes de água quente e água fria, e após isso, será medida a temperatura final das duas.",
  item: {
    a: "Dois copos transparentes",
    b: "Água",
    c: "Outro líquido (pode ser suco, leite, refrigerante, etc.)",
    d: "Termômetro",
    e: "Caneta e papel para registro de observações",
    f:"",
    g:"",
    h:"",
    i:"",
    j:"",
  },
  procedimento: "Parte 1: Preparação<br>Encha um copo com água à temperatura ambiente.<br>Encha outro copo com o líquido escolhido à temperatura ambiente.<br>Certifique-se de que ambos os líquidos estão à mesma temperatura inicial.<br>Parte 2: Medição da Temperatura Inicial<br>Meça e registre a temperatura inicial da água usando o termômetro.<br>Meça e registre a temperatura inicial do outro líquido usando o termômetro.<br>Anote as temperaturas iniciais em seu registro.<br>Parte 3: Mistura dos Líquidos<br>Despeje o líquido do segundo copo (por exemplo, suco) no copo com água.<br>Mexa suavemente os líquidos para garantir uma mistura uniforme.<br>Parte 4: Medição da Temperatura Final<br>Meça e registre a temperatura final da mistura usando o termômetro.<br>Anote a temperatura final em seu registro.<br>Parte 5: Análise de Resultados<br>Compare as temperaturas iniciais e finais da água e do outro líquido antes e depois da mistura.<br>Discuta como a mistura afetou a temperatura resultante, se houve uma mudança e se a temperatura final ficou entre as temperaturas iniciais dos líquidos.",
  video: "https://youtu.be/XvfPQ-U8HN8?si=vKgJBiR76y2ma1Zv",
}
];
